theme: jekyll-theme-cayman
title: Welcome to the Arf Hashtag Bot's homepage!
description:Send a photo and generate auto hashtag for your photos with this bot on Facebook Messenger, Telegram and Skype channels.
